# This script prints out a series of jokes, 
# illustrating various ways to use quotes and print strings into the console.
print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black hole!')
print()
print('Knock knock.')
input()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('Interupting cow wh', end='')
print('-MOO!')